/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: mesg.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "mesg.pb-c.h"
void   mesg_online__init
                     (MesgOnline         *message)
{
  static MesgOnline init_value = MESG_ONLINE__INIT;
  *message = init_value;
}
size_t mesg_online__get_packed_size
                     (const MesgOnline *message)
{
  assert(message->base.descriptor == &mesg_online__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mesg_online__pack
                     (const MesgOnline *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mesg_online__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mesg_online__pack_to_buffer
                     (const MesgOnline *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mesg_online__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MesgOnline *
       mesg_online__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MesgOnline *)
     protobuf_c_message_unpack (&mesg_online__descriptor,
                                allocator, len, data);
}
void   mesg_online__free_unpacked
                     (MesgOnline *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &mesg_online__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mesg_online_ack__init
                     (MesgOnlineAck         *message)
{
  static MesgOnlineAck init_value = MESG_ONLINE_ACK__INIT;
  *message = init_value;
}
size_t mesg_online_ack__get_packed_size
                     (const MesgOnlineAck *message)
{
  assert(message->base.descriptor == &mesg_online_ack__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mesg_online_ack__pack
                     (const MesgOnlineAck *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mesg_online_ack__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mesg_online_ack__pack_to_buffer
                     (const MesgOnlineAck *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mesg_online_ack__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MesgOnlineAck *
       mesg_online_ack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MesgOnlineAck *)
     protobuf_c_message_unpack (&mesg_online_ack__descriptor,
                                allocator, len, data);
}
void   mesg_online_ack__free_unpacked
                     (MesgOnlineAck *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &mesg_online_ack__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mesg_kick__init
                     (MesgKick         *message)
{
  static MesgKick init_value = MESG_KICK__INIT;
  *message = init_value;
}
size_t mesg_kick__get_packed_size
                     (const MesgKick *message)
{
  assert(message->base.descriptor == &mesg_kick__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mesg_kick__pack
                     (const MesgKick *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mesg_kick__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mesg_kick__pack_to_buffer
                     (const MesgKick *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mesg_kick__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MesgKick *
       mesg_kick__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MesgKick *)
     protobuf_c_message_unpack (&mesg_kick__descriptor,
                                allocator, len, data);
}
void   mesg_kick__free_unpacked
                     (MesgKick *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &mesg_kick__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   browser_plugin_info__init
                     (BrowserPluginInfo         *message)
{
  static BrowserPluginInfo init_value = BROWSER_PLUGIN_INFO__INIT;
  *message = init_value;
}
size_t browser_plugin_info__get_packed_size
                     (const BrowserPluginInfo *message)
{
  assert(message->base.descriptor == &browser_plugin_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t browser_plugin_info__pack
                     (const BrowserPluginInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &browser_plugin_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t browser_plugin_info__pack_to_buffer
                     (const BrowserPluginInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &browser_plugin_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BrowserPluginInfo *
       browser_plugin_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BrowserPluginInfo *)
     protobuf_c_message_unpack (&browser_plugin_info__descriptor,
                                allocator, len, data);
}
void   browser_plugin_info__free_unpacked
                     (BrowserPluginInfo *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &browser_plugin_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   browser_useragent_info__init
                     (BrowserUseragentInfo         *message)
{
  static BrowserUseragentInfo init_value = BROWSER_USERAGENT_INFO__INIT;
  *message = init_value;
}
size_t browser_useragent_info__get_packed_size
                     (const BrowserUseragentInfo *message)
{
  assert(message->base.descriptor == &browser_useragent_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t browser_useragent_info__pack
                     (const BrowserUseragentInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &browser_useragent_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t browser_useragent_info__pack_to_buffer
                     (const BrowserUseragentInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &browser_useragent_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BrowserUseragentInfo *
       browser_useragent_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BrowserUseragentInfo *)
     protobuf_c_message_unpack (&browser_useragent_info__descriptor,
                                allocator, len, data);
}
void   browser_useragent_info__free_unpacked
                     (BrowserUseragentInfo *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &browser_useragent_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   browser_screen_info__init
                     (BrowserScreenInfo         *message)
{
  static BrowserScreenInfo init_value = BROWSER_SCREEN_INFO__INIT;
  *message = init_value;
}
size_t browser_screen_info__get_packed_size
                     (const BrowserScreenInfo *message)
{
  assert(message->base.descriptor == &browser_screen_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t browser_screen_info__pack
                     (const BrowserScreenInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &browser_screen_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t browser_screen_info__pack_to_buffer
                     (const BrowserScreenInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &browser_screen_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BrowserScreenInfo *
       browser_screen_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BrowserScreenInfo *)
     protobuf_c_message_unpack (&browser_screen_info__descriptor,
                                allocator, len, data);
}
void   browser_screen_info__free_unpacked
                     (BrowserScreenInfo *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &browser_screen_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mesg_browser_env__init
                     (MesgBrowserEnv         *message)
{
  static MesgBrowserEnv init_value = MESG_BROWSER_ENV__INIT;
  *message = init_value;
}
size_t mesg_browser_env__get_packed_size
                     (const MesgBrowserEnv *message)
{
  assert(message->base.descriptor == &mesg_browser_env__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mesg_browser_env__pack
                     (const MesgBrowserEnv *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mesg_browser_env__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mesg_browser_env__pack_to_buffer
                     (const MesgBrowserEnv *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mesg_browser_env__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MesgBrowserEnv *
       mesg_browser_env__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MesgBrowserEnv *)
     protobuf_c_message_unpack (&mesg_browser_env__descriptor,
                                allocator, len, data);
}
void   mesg_browser_env__free_unpacked
                     (MesgBrowserEnv *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &mesg_browser_env__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mesg_browser_env_ack__init
                     (MesgBrowserEnvAck         *message)
{
  static MesgBrowserEnvAck init_value = MESG_BROWSER_ENV_ACK__INIT;
  *message = init_value;
}
size_t mesg_browser_env_ack__get_packed_size
                     (const MesgBrowserEnvAck *message)
{
  assert(message->base.descriptor == &mesg_browser_env_ack__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mesg_browser_env_ack__pack
                     (const MesgBrowserEnvAck *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mesg_browser_env_ack__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mesg_browser_env_ack__pack_to_buffer
                     (const MesgBrowserEnvAck *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mesg_browser_env_ack__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MesgBrowserEnvAck *
       mesg_browser_env_ack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MesgBrowserEnvAck *)
     protobuf_c_message_unpack (&mesg_browser_env_ack__descriptor,
                                allocator, len, data);
}
void   mesg_browser_env_ack__free_unpacked
                     (MesgBrowserEnvAck *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &mesg_browser_env_ack__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mesg_event_statistic__init
                     (MesgEventStatistic         *message)
{
  static MesgEventStatistic init_value = MESG_EVENT_STATISTIC__INIT;
  *message = init_value;
}
size_t mesg_event_statistic__get_packed_size
                     (const MesgEventStatistic *message)
{
  assert(message->base.descriptor == &mesg_event_statistic__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mesg_event_statistic__pack
                     (const MesgEventStatistic *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mesg_event_statistic__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mesg_event_statistic__pack_to_buffer
                     (const MesgEventStatistic *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mesg_event_statistic__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MesgEventStatistic *
       mesg_event_statistic__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MesgEventStatistic *)
     protobuf_c_message_unpack (&mesg_event_statistic__descriptor,
                                allocator, len, data);
}
void   mesg_event_statistic__free_unpacked
                     (MesgEventStatistic *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &mesg_event_statistic__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mesg_event_statistic_ack__init
                     (MesgEventStatisticAck         *message)
{
  static MesgEventStatisticAck init_value = MESG_EVENT_STATISTIC_ACK__INIT;
  *message = init_value;
}
size_t mesg_event_statistic_ack__get_packed_size
                     (const MesgEventStatisticAck *message)
{
  assert(message->base.descriptor == &mesg_event_statistic_ack__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mesg_event_statistic_ack__pack
                     (const MesgEventStatisticAck *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mesg_event_statistic_ack__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mesg_event_statistic_ack__pack_to_buffer
                     (const MesgEventStatisticAck *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mesg_event_statistic_ack__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MesgEventStatisticAck *
       mesg_event_statistic_ack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MesgEventStatisticAck *)
     protobuf_c_message_unpack (&mesg_event_statistic_ack__descriptor,
                                allocator, len, data);
}
void   mesg_event_statistic_ack__free_unpacked
                     (MesgEventStatisticAck *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &mesg_event_statistic_ack__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mesg_lsnd_info__init
                     (MesgLsndInfo         *message)
{
  static MesgLsndInfo init_value = MESG_LSND_INFO__INIT;
  *message = init_value;
}
size_t mesg_lsnd_info__get_packed_size
                     (const MesgLsndInfo *message)
{
  assert(message->base.descriptor == &mesg_lsnd_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mesg_lsnd_info__pack
                     (const MesgLsndInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mesg_lsnd_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mesg_lsnd_info__pack_to_buffer
                     (const MesgLsndInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mesg_lsnd_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MesgLsndInfo *
       mesg_lsnd_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MesgLsndInfo *)
     protobuf_c_message_unpack (&mesg_lsnd_info__descriptor,
                                allocator, len, data);
}
void   mesg_lsnd_info__free_unpacked
                     (MesgLsndInfo *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &mesg_lsnd_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mesg_frwd_info__init
                     (MesgFrwdInfo         *message)
{
  static MesgFrwdInfo init_value = MESG_FRWD_INFO__INIT;
  *message = init_value;
}
size_t mesg_frwd_info__get_packed_size
                     (const MesgFrwdInfo *message)
{
  assert(message->base.descriptor == &mesg_frwd_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mesg_frwd_info__pack
                     (const MesgFrwdInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mesg_frwd_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mesg_frwd_info__pack_to_buffer
                     (const MesgFrwdInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mesg_frwd_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MesgFrwdInfo *
       mesg_frwd_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MesgFrwdInfo *)
     protobuf_c_message_unpack (&mesg_frwd_info__descriptor,
                                allocator, len, data);
}
void   mesg_frwd_info__free_unpacked
                     (MesgFrwdInfo *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &mesg_frwd_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor mesg_online__field_descriptors[4] =
{
  {
    "sid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MesgOnline, sid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "token",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MesgOnline, token),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "app",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MesgOnline, app),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MesgOnline, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mesg_online__field_indices_by_name[] = {
  2,   /* field[2] = app */
  0,   /* field[0] = sid */
  1,   /* field[1] = token */
  3,   /* field[3] = version */
};
static const ProtobufCIntRange mesg_online__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor mesg_online__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mesg_online",
  "MesgOnline",
  "MesgOnline",
  "",
  sizeof(MesgOnline),
  4,
  mesg_online__field_descriptors,
  mesg_online__field_indices_by_name,
  1,  mesg_online__number_ranges,
  (ProtobufCMessageInit) mesg_online__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mesg_online_ack__field_descriptors[5] =
{
  {
    "sid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MesgOnlineAck, sid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "app",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MesgOnlineAck, app),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MesgOnlineAck, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "code",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MesgOnlineAck, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errmsg",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MesgOnlineAck, errmsg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mesg_online_ack__field_indices_by_name[] = {
  1,   /* field[1] = app */
  3,   /* field[3] = code */
  4,   /* field[4] = errmsg */
  0,   /* field[0] = sid */
  2,   /* field[2] = version */
};
static const ProtobufCIntRange mesg_online_ack__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor mesg_online_ack__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mesg_online_ack",
  "MesgOnlineAck",
  "MesgOnlineAck",
  "",
  sizeof(MesgOnlineAck),
  5,
  mesg_online_ack__field_descriptors,
  mesg_online_ack__field_indices_by_name,
  1,  mesg_online_ack__number_ranges,
  (ProtobufCMessageInit) mesg_online_ack__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mesg_kick__field_descriptors[2] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MesgKick, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errmsg",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MesgKick, errmsg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mesg_kick__field_indices_by_name[] = {
  0,   /* field[0] = code */
  1,   /* field[1] = errmsg */
};
static const ProtobufCIntRange mesg_kick__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor mesg_kick__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mesg_kick",
  "MesgKick",
  "MesgKick",
  "",
  sizeof(MesgKick),
  2,
  mesg_kick__field_descriptors,
  mesg_kick__field_indices_by_name,
  1,  mesg_kick__number_ranges,
  (ProtobufCMessageInit) mesg_kick__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor browser_plugin_info__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(BrowserPluginInfo, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "desc",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(BrowserPluginInfo, desc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned browser_plugin_info__field_indices_by_name[] = {
  1,   /* field[1] = desc */
  0,   /* field[0] = name */
};
static const ProtobufCIntRange browser_plugin_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor browser_plugin_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "browser_plugin_info",
  "BrowserPluginInfo",
  "BrowserPluginInfo",
  "",
  sizeof(BrowserPluginInfo),
  2,
  browser_plugin_info__field_descriptors,
  browser_plugin_info__field_indices_by_name,
  1,  browser_plugin_info__number_ranges,
  (ProtobufCMessageInit) browser_plugin_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor browser_useragent_info__field_descriptors[1] =
{
  {
    "ua",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(BrowserUseragentInfo, ua),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned browser_useragent_info__field_indices_by_name[] = {
  0,   /* field[0] = ua */
};
static const ProtobufCIntRange browser_useragent_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor browser_useragent_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "browser_useragent_info",
  "BrowserUseragentInfo",
  "BrowserUseragentInfo",
  "",
  sizeof(BrowserUseragentInfo),
  1,
  browser_useragent_info__field_descriptors,
  browser_useragent_info__field_indices_by_name,
  1,  browser_useragent_info__number_ranges,
  (ProtobufCMessageInit) browser_useragent_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor browser_screen_info__field_descriptors[10] =
{
  {
    "width",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(BrowserScreenInfo, has_width),
    offsetof(BrowserScreenInfo, width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "height",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(BrowserScreenInfo, has_height),
    offsetof(BrowserScreenInfo, height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "avail_width",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(BrowserScreenInfo, has_avail_width),
    offsetof(BrowserScreenInfo, avail_width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "avail_height",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(BrowserScreenInfo, has_avail_height),
    offsetof(BrowserScreenInfo, avail_height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "avail_left",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(BrowserScreenInfo, has_avail_left),
    offsetof(BrowserScreenInfo, avail_left),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "avail_top",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(BrowserScreenInfo, has_avail_top),
    offsetof(BrowserScreenInfo, avail_top),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "outer_width",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(BrowserScreenInfo, has_outer_width),
    offsetof(BrowserScreenInfo, outer_width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "outer_height",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(BrowserScreenInfo, has_outer_height),
    offsetof(BrowserScreenInfo, outer_height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inner_width",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(BrowserScreenInfo, has_inner_width),
    offsetof(BrowserScreenInfo, inner_width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inner_height",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(BrowserScreenInfo, has_inner_height),
    offsetof(BrowserScreenInfo, inner_height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned browser_screen_info__field_indices_by_name[] = {
  3,   /* field[3] = avail_height */
  4,   /* field[4] = avail_left */
  5,   /* field[5] = avail_top */
  2,   /* field[2] = avail_width */
  1,   /* field[1] = height */
  9,   /* field[9] = inner_height */
  8,   /* field[8] = inner_width */
  7,   /* field[7] = outer_height */
  6,   /* field[6] = outer_width */
  0,   /* field[0] = width */
};
static const ProtobufCIntRange browser_screen_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor browser_screen_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "browser_screen_info",
  "BrowserScreenInfo",
  "BrowserScreenInfo",
  "",
  sizeof(BrowserScreenInfo),
  10,
  browser_screen_info__field_descriptors,
  browser_screen_info__field_indices_by_name,
  1,  browser_screen_info__number_ranges,
  (ProtobufCMessageInit) browser_screen_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mesg_browser_env__field_descriptors[3] =
{
  {
    "plugin",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MesgBrowserEnv, plugin),
    &browser_plugin_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ua",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MesgBrowserEnv, ua),
    &browser_useragent_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "screen",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MesgBrowserEnv, screen),
    &browser_screen_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mesg_browser_env__field_indices_by_name[] = {
  0,   /* field[0] = plugin */
  2,   /* field[2] = screen */
  1,   /* field[1] = ua */
};
static const ProtobufCIntRange mesg_browser_env__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor mesg_browser_env__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mesg_browser_env",
  "MesgBrowserEnv",
  "MesgBrowserEnv",
  "",
  sizeof(MesgBrowserEnv),
  3,
  mesg_browser_env__field_descriptors,
  mesg_browser_env__field_indices_by_name,
  1,  mesg_browser_env__number_ranges,
  (ProtobufCMessageInit) mesg_browser_env__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mesg_browser_env_ack__field_descriptors[2] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MesgBrowserEnvAck, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errmsg",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MesgBrowserEnvAck, errmsg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mesg_browser_env_ack__field_indices_by_name[] = {
  0,   /* field[0] = code */
  1,   /* field[1] = errmsg */
};
static const ProtobufCIntRange mesg_browser_env_ack__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor mesg_browser_env_ack__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mesg_browser_env_ack",
  "MesgBrowserEnvAck",
  "MesgBrowserEnvAck",
  "",
  sizeof(MesgBrowserEnvAck),
  2,
  mesg_browser_env_ack__field_descriptors,
  mesg_browser_env_ack__field_indices_by_name,
  1,  mesg_browser_env_ack__number_ranges,
  (ProtobufCMessageInit) mesg_browser_env_ack__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mesg_event_statistic__field_descriptors[3] =
{
  {
    "ctrl",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(MesgEventStatistic, ctrl),
    &ctrl_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "event",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(MesgEventStatistic, event),
    &event_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "count",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MesgEventStatistic, count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mesg_event_statistic__field_indices_by_name[] = {
  2,   /* field[2] = count */
  0,   /* field[0] = ctrl */
  1,   /* field[1] = event */
};
static const ProtobufCIntRange mesg_event_statistic__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor mesg_event_statistic__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mesg_event_statistic",
  "MesgEventStatistic",
  "MesgEventStatistic",
  "",
  sizeof(MesgEventStatistic),
  3,
  mesg_event_statistic__field_descriptors,
  mesg_event_statistic__field_indices_by_name,
  1,  mesg_event_statistic__number_ranges,
  (ProtobufCMessageInit) mesg_event_statistic__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mesg_event_statistic_ack__field_descriptors[2] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MesgEventStatisticAck, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errmsg",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MesgEventStatisticAck, errmsg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mesg_event_statistic_ack__field_indices_by_name[] = {
  0,   /* field[0] = code */
  1,   /* field[1] = errmsg */
};
static const ProtobufCIntRange mesg_event_statistic_ack__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor mesg_event_statistic_ack__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mesg_event_statistic_ack",
  "MesgEventStatisticAck",
  "MesgEventStatisticAck",
  "",
  sizeof(MesgEventStatisticAck),
  2,
  mesg_event_statistic_ack__field_descriptors,
  mesg_event_statistic_ack__field_indices_by_name,
  1,  mesg_event_statistic_ack__number_ranges,
  (ProtobufCMessageInit) mesg_event_statistic_ack__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mesg_lsnd_info__field_descriptors[7] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MesgLsndInfo, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nid",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MesgLsndInfo, nid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "opid",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MesgLsndInfo, opid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nation",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MesgLsndInfo, nation),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ip",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MesgLsndInfo, ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MesgLsndInfo, port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connections",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MesgLsndInfo, connections),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mesg_lsnd_info__field_indices_by_name[] = {
  6,   /* field[6] = connections */
  4,   /* field[4] = ip */
  3,   /* field[3] = nation */
  1,   /* field[1] = nid */
  2,   /* field[2] = opid */
  5,   /* field[5] = port */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange mesg_lsnd_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor mesg_lsnd_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mesg_lsnd_info",
  "MesgLsndInfo",
  "MesgLsndInfo",
  "",
  sizeof(MesgLsndInfo),
  7,
  mesg_lsnd_info__field_descriptors,
  mesg_lsnd_info__field_indices_by_name,
  1,  mesg_lsnd_info__number_ranges,
  (ProtobufCMessageInit) mesg_lsnd_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mesg_frwd_info__field_descriptors[4] =
{
  {
    "nid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MesgFrwdInfo, nid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ip",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MesgFrwdInfo, ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "forward_port",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MesgFrwdInfo, forward_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "backend_port",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MesgFrwdInfo, backend_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mesg_frwd_info__field_indices_by_name[] = {
  3,   /* field[3] = backend_port */
  2,   /* field[2] = forward_port */
  1,   /* field[1] = ip */
  0,   /* field[0] = nid */
};
static const ProtobufCIntRange mesg_frwd_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor mesg_frwd_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "mesg_frwd_info",
  "MesgFrwdInfo",
  "MesgFrwdInfo",
  "",
  sizeof(MesgFrwdInfo),
  4,
  mesg_frwd_info__field_descriptors,
  mesg_frwd_info__field_indices_by_name,
  1,  mesg_frwd_info__number_ranges,
  (ProtobufCMessageInit) mesg_frwd_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue ctrl_type__enum_values_by_number[8] =
{
  { "CTL_IBX_USR", "CTRL_TYPE__CTL_IBX_USR", 0 },
  { "CTL_IBX_PWD", "CTRL_TYPE__CTL_IBX_PWD", 1 },
  { "CTL_IBX_IMG", "CTRL_TYPE__CTL_IBX_IMG", 2 },
  { "CTL_BTN_IMG", "CTRL_TYPE__CTL_BTN_IMG", 3 },
  { "CTL_IBX_TEL", "CTRL_TYPE__CTL_IBX_TEL", 4 },
  { "CTL_IBX_SMS", "CTRL_TYPE__CTL_IBX_SMS", 5 },
  { "CTL_BTN_SMS", "CTRL_TYPE__CTL_BTN_SMS", 6 },
  { "CTL_BTN_LGN", "CTRL_TYPE__CTL_BTN_LGN", 7 },
};
static const ProtobufCIntRange ctrl_type__value_ranges[] = {
{0, 0},{0, 8}
};
const ProtobufCEnumValueIndex ctrl_type__enum_values_by_name[8] =
{
  { "CTL_BTN_IMG", 3 },
  { "CTL_BTN_LGN", 7 },
  { "CTL_BTN_SMS", 6 },
  { "CTL_IBX_IMG", 2 },
  { "CTL_IBX_PWD", 1 },
  { "CTL_IBX_SMS", 5 },
  { "CTL_IBX_TEL", 4 },
  { "CTL_IBX_USR", 0 },
};
const ProtobufCEnumDescriptor ctrl_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ctrl_type",
  "ctrl_type",
  "CtrlType",
  "",
  8,
  ctrl_type__enum_values_by_number,
  8,
  ctrl_type__enum_values_by_name,
  1,
  ctrl_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
const ProtobufCEnumValue event_type__enum_values_by_number[16] =
{
  { "EV_CHANGE", "EVENT_TYPE__EV_CHANGE", 0 },
  { "EV_CLICK", "EVENT_TYPE__EV_CLICK", 1 },
  { "EV_DBLCLICK", "EVENT_TYPE__EV_DBLCLICK", 2 },
  { "EV_FOCUS", "EVENT_TYPE__EV_FOCUS", 3 },
  { "EV_KEYDOWN", "EVENT_TYPE__EV_KEYDOWN", 4 },
  { "EV_KEYPRESS", "EVENT_TYPE__EV_KEYPRESS", 5 },
  { "EV_KEYUP", "EVENT_TYPE__EV_KEYUP", 6 },
  { "EV_MOUSEDOWN", "EVENT_TYPE__EV_MOUSEDOWN", 7 },
  { "EV_MOUSEMOVE", "EVENT_TYPE__EV_MOUSEMOVE", 8 },
  { "EV_MOUSEOUT", "EVENT_TYPE__EV_MOUSEOUT", 9 },
  { "EV_MOUSEOVER", "EVENT_TYPE__EV_MOUSEOVER", 10 },
  { "EV_MOUSEUP", "EVENT_TYPE__EV_MOUSEUP", 11 },
  { "EV_TOUCHSTART", "EVENT_TYPE__EV_TOUCHSTART", 12 },
  { "EV_TOUCHMOVE", "EVENT_TYPE__EV_TOUCHMOVE", 13 },
  { "EV_TOUCHEND", "EVENT_TYPE__EV_TOUCHEND", 14 },
  { "EV_TOUCHCANCEL", "EVENT_TYPE__EV_TOUCHCANCEL", 15 },
};
static const ProtobufCIntRange event_type__value_ranges[] = {
{0, 0},{0, 16}
};
const ProtobufCEnumValueIndex event_type__enum_values_by_name[16] =
{
  { "EV_CHANGE", 0 },
  { "EV_CLICK", 1 },
  { "EV_DBLCLICK", 2 },
  { "EV_FOCUS", 3 },
  { "EV_KEYDOWN", 4 },
  { "EV_KEYPRESS", 5 },
  { "EV_KEYUP", 6 },
  { "EV_MOUSEDOWN", 7 },
  { "EV_MOUSEMOVE", 8 },
  { "EV_MOUSEOUT", 9 },
  { "EV_MOUSEOVER", 10 },
  { "EV_MOUSEUP", 11 },
  { "EV_TOUCHCANCEL", 15 },
  { "EV_TOUCHEND", 14 },
  { "EV_TOUCHMOVE", 13 },
  { "EV_TOUCHSTART", 12 },
};
const ProtobufCEnumDescriptor event_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "event_type",
  "event_type",
  "EventType",
  "",
  16,
  event_type__enum_values_by_number,
  16,
  event_type__enum_values_by_name,
  1,
  event_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
